import type { AssessmentDefinition } from "@/lib/assessment/types";
import welcomeScene from "@/assets/checkin-20.png.asset.json";
import snackScene from "@/assets/checkin-21.png.asset.json";
import celebrationScene from "@/assets/checkin-22.png.asset.json";

// TATI Junior (ages 8–12), Ghana. Scenario-style questions, never exam language.
// Pure data — no UI, no database access.

export const savePreAssessment: AssessmentDefinition = {
  id: "save-pre",
  trackId: "save",
  assessmentType: "pre",
  title: "Before we begin",
  shortTitle: "Money Check-In",
  introHeadline: "Let's see how you think about money! 🧠",
  intro:
    "There are no grades or scores here! Just choose what you think you would do in everyday life.",
  introImageUrl: welcomeScene.url,
  introImageBadge: "Meet Kwesi",
  introTopics: [
    { icon: "🍎", label: "Buying snacks" },
    { icon: "💰", label: "Saving cedis" },
    { icon: "🤝", label: "Sharing" },
  ],
  estimatedMinutes: 5,
  startingWallet: 10,
  outro:
    "We've learned a little about how you think about everyday money choices. Now your TATI adventure begins!",
  outroImageUrl: celebrationScene.url,
  outroImageBadge: "Profile Unlocked",
  showScoreToChild: false,
  questions: [
    {
      id: "p1",
      assessmentType: "pre",
      competency: "spending-decisions",
      illustration: "🧺",
      topic: "Saturday Treat",
      imageUrl: snackScene.url,
      imageBadge: "GH₵10 Gift",
      hint: "There are no wrong answers — pick the plan that suits you best!",
      question: "Auntie Akosua gives you GH₵10 on Saturday. What do you do first?",
      options: [
        {
          id: "a",
          label: "Spend it all at the food stall",
          description: "Enjoy the moment with friends today.",
          icon: "🍢",
        },
        {
          id: "b",
          label: "Keep some of it and spend the rest",
          description: "Treat myself a little and still grow my savings.",
          icon: "🪙",
        },
        {
          id: "c",
          label: "Keep all of it for something bigger",
          description: "Put every cedi away for a special goal.",
          icon: "🎯",
        },
        {
          id: "d",
          label: "Give it to a friend to hold",
          description: "Ask someone else to keep it safe.",
          icon: "🤝",
        },
      ],
      idealOptionId: "b",
      feedback:
        "Keeping a part of your money and enjoying a part of it is a habit many savers use. We'll practise it together.",
    },
    {
      id: "p2",
      assessmentType: "pre",
      competency: "saving",
      illustration: "🐷",
      question: "What does 'saving' mean to you?",
      options: [
        { id: "a", label: "Money you keep for later" },
        { id: "b", label: "Money you are not allowed to touch" },
        { id: "c", label: "Money you hide from everyone" },
        { id: "d", label: "Money you get from grown-ups" },
      ],
      idealOptionId: "a",
      feedback: "Saving simply means money you keep now so it can help you later.",
    },
    {
      id: "p3",
      assessmentType: "pre",
      competency: "money-safety",
      illustration: "🔐",
      question: "Where is the safest place for your savings?",
      options: [
        { id: "a", label: "In your school bag" },
        { id: "b", label: "In your pocket" },
        { id: "c", label: "In a money box, or with a trusted adult, bank or mobile wallet" },
        { id: "d", label: "Under a stone outside" },
      ],
      idealOptionId: "c",
      feedback:
        "Money kept in a safe place — a money box at home, a bank, or Mobile Money — is much harder to lose.",
    },
    {
      id: "p4",
      assessmentType: "pre",
      competency: "goal-setting",
      illustration: "⚽",
      question: "You want a football that costs GH₵60. You get GH₵5 each week. What helps most?",
      options: [
        { id: "a", label: "Hope somebody buys it for you" },
        { id: "b", label: "Save GH₵5 every week and count the weeks" },
        { id: "c", label: "Forget about it" },
        { id: "d", label: "Borrow the money from a friend" },
      ],
      idealOptionId: "b",
      feedback:
        "A goal plus a plan makes big things possible. GH₵5 a week reaches GH₵60 in 12 weeks.",
    },
    {
      id: "p5",
      assessmentType: "pre",
      competency: "financial-resilience",
      illustration: "🌱",
      question:
        "Kofi saved for two weeks then spent everything on sweets. What would you tell him?",
      options: [
        { id: "a", label: "He wasted it all" },
        { id: "b", label: "He can start again and keep part of his money next time" },
        { id: "c", label: "He should never buy sweets" },
        { id: "d", label: "He should stop saving" },
      ],
      idealOptionId: "b",
      feedback: "Every decision teaches us something. Plans can always be adjusted.",
    },
    {
      id: "p6",
      assessmentType: "pre",
      competency: "needs-vs-wants",
      illustration: "🎒",
      question:
        "School starts on Monday. You have GH₵15. Your sandals are torn and there is a new sticker book you love. What comes first?",
      options: [
        { id: "a", label: "The sandals — you need them for school" },
        { id: "b", label: "The sticker book — you really want it" },
        { id: "c", label: "Neither, keep the money in your bag" },
      ],
      idealOptionId: "a",
      feedback:
        "Things we need usually come before things we want. Wants can still have their turn later.",
    },
    {
      id: "p7",
      assessmentType: "pre",
      competency: "earning",
      illustration: "🧹",
      question: "Which of these is a way a child like you could earn money?",
      options: [
        { id: "a", label: "Helping at Uncle Yaw's shop on Saturday" },
        { id: "b", label: "Asking a friend for their money" },
        { id: "c", label: "Waiting until someone gives you some" },
      ],
      idealOptionId: "a",
      feedback:
        "Earning means giving something useful — your help, your time, your skill — and getting money back.",
    },
    {
      id: "p8",
      assessmentType: "pre",
      competency: "tracking-money",
      illustration: "📓",
      question: "Ama can never remember where her money went. What could help her?",
      options: [
        { id: "a", label: "Write down what she spends in a small book" },
        { id: "b", label: "Try harder to remember" },
        { id: "c", label: "Stop carrying money" },
      ],
      idealOptionId: "a",
      feedback: "Writing it down makes money easy to follow. You always know what is left.",
    },
    {
      id: "p9",
      assessmentType: "pre",
      competency: "budgeting",
      illustration: "🍽️",
      question: "You get GH₵10 for the whole school week. What is a good plan?",
      options: [
        { id: "a", label: "Spend GH₵2 a day and keep the rest" },
        { id: "b", label: "Spend GH₵8 on Monday and see what happens" },
        { id: "c", label: "Spend it all on the first day" },
      ],
      idealOptionId: "a",
      feedback: "Sharing your money across the days means there is still some on Friday.",
    },
    {
      id: "p10",
      assessmentType: "pre",
      competency: "borrowing-lending",
      illustration: "🤝",
      question: "Your friend Esi borrows GH₵5 from you. What is a fair thing to agree?",
      options: [
        { id: "a", label: "When she will pay it back" },
        { id: "b", label: "Nothing, just hope she remembers" },
        { id: "c", label: "Tell everyone in class about it" },
      ],
      idealOptionId: "a",
      feedback: "Agreeing when money comes back keeps friendships easy and money safe.",
    },
  ],
};

export const savePostAssessment: AssessmentDefinition = {
  id: "save-post",
  trackId: "save",
  assessmentType: "post",
  title: "Let's see what you've picked up",
  intro: "Same kind of money stories as before. Answer the way you would act now.",
  outro: "Beautiful work. Look how much you thought about each choice!",
  showScoreToChild: true,
  questions: [
    {
      id: "q1",
      assessmentType: "post",
      competency: "spending-decisions",
      illustration: "🏪",
      question: "You receive GH₵20 for helping at your uncle's shop. What is a strong first step?",
      options: [
        { id: "a", label: "Decide how much to keep before you spend anything" },
        { id: "b", label: "Buy something quickly before you change your mind" },
        { id: "c", label: "Carry it around all week" },
        { id: "d", label: "Split it with everyone" },
      ],
      idealOptionId: "a",
      feedback:
        "Deciding first is what savers do. Spending is easier to control once the saving is set aside.",
    },
    {
      id: "q2",
      assessmentType: "post",
      competency: "goal-setting",
      illustration: "👟",
      question: "Which one is a saving goal?",
      options: [
        { id: "a", label: "GH₵40 for new school shoes by December" },
        { id: "b", label: "Some money, some day" },
        { id: "c", label: "Whatever is left over" },
        { id: "d", label: "As much as possible" },
      ],
      idealOptionId: "a",
      feedback: "A good goal has an amount and a time. That's what makes it easy to follow.",
    },
    {
      id: "q3",
      assessmentType: "post",
      competency: "money-safety",
      illustration: "📱",
      question: "Kwabena keeps his savings loose in his school bag. What would you suggest?",
      options: [
        { id: "a", label: "A money box at home, or a bank or Mobile Money account" },
        { id: "b", label: "A different pocket" },
        { id: "c", label: "Giving it to a classmate" },
      ],
      idealOptionId: "a",
      feedback: "Safe places protect savings from getting lost or spent by mistake.",
    },
    {
      id: "q4",
      assessmentType: "post",
      competency: "needs-vs-wants",
      illustration: "🥤",
      question: "You are saving for a bicycle. A cold drink costs GH₵3 every break time. What now?",
      options: [
        { id: "a", label: "Buy a drink some days and put the other days into the bicycle" },
        { id: "b", label: "Buy a drink every single day" },
        { id: "c", label: "Never drink anything again" },
      ],
      idealOptionId: "a",
      feedback: "Savers balance today and tomorrow. You don't have to give up everything.",
    },
    {
      id: "q5",
      assessmentType: "post",
      competency: "tracking-money",
      illustration: "🧮",
      question: "You want to know if your saving plan is working. What do you do?",
      options: [
        { id: "a", label: "Count your savings each week and compare with your goal" },
        { id: "b", label: "Guess" },
        { id: "c", label: "Wait until the end and see" },
      ],
      idealOptionId: "a",
      feedback: "Checking often tells you early if you need to adjust your plan.",
    },
    {
      id: "q6",
      assessmentType: "post",
      competency: "budgeting",
      illustration: "📊",
      question: "You get GH₵12 this week. Which plan keeps your goal moving?",
      options: [
        { id: "a", label: "GH₵6 to save, GH₵6 to spend" },
        { id: "b", label: "GH₵12 to spend" },
        { id: "c", label: "Decide later, when the money is gone" },
      ],
      idealOptionId: "a",
      feedback: "Giving each cedi a job before you spend is what a budget really is.",
    },
    {
      id: "q7",
      assessmentType: "post",
      competency: "financial-resilience",
      illustration: "🌦️",
      question:
        "You had to use your savings for something unexpected. How do you feel about your goal?",
      options: [
        { id: "a", label: "The goal is still there — I start adding again" },
        { id: "b", label: "The goal is finished" },
        { id: "c", label: "Saving doesn't work" },
      ],
      idealOptionId: "a",
      feedback: "Plans bend, they don't break. Starting again is part of saving.",
    },
    {
      id: "q8",
      assessmentType: "post",
      competency: "earning",
      illustration: "🧺",
      question: "You are GH₵10 short of your goal. What could help most?",
      options: [
        { id: "a", label: "Offer to help a neighbour with a small job" },
        { id: "b", label: "Wait and hope" },
        { id: "c", label: "Change the goal to something you don't want" },
      ],
      idealOptionId: "a",
      feedback: "Earning a little extra is one more way to reach a goal you care about.",
    },
    {
      id: "q9",
      assessmentType: "post",
      competency: "borrowing-lending",
      illustration: "🕊️",
      question: "Yaw wants to borrow GH₵10 from your savings. What is wise?",
      options: [
        { id: "a", label: "Talk with a trusted adult and agree when it comes back" },
        { id: "b", label: "Give all your savings quickly" },
        { id: "c", label: "Say yes and never mention it again" },
      ],
      idealOptionId: "a",
      feedback:
        "Clear agreements and a grown-up's help keep both your money and your friendship safe.",
    },
    {
      id: "q10",
      assessmentType: "post",
      competency: "saving",
      illustration: "🏆",
      question: "What makes saving easier over time?",
      options: [
        { id: "a", label: "Saving a small amount regularly" },
        { id: "b", label: "Saving only when you feel like it" },
        { id: "c", label: "Waiting for one big amount" },
      ],
      idealOptionId: "a",
      feedback: "Small and regular beats big and rare, almost every time.",
    },
  ],
};
