import type { ScenarioDefinition } from "@/lib/scenario/types";
import playground from "@/assets/scene-83.png.asset.json";
import veranda from "@/assets/scene-84.png.asset.json";
import repaymentScene from "@/assets/scene-85.png.asset.json";
import marketScene from "@/assets/scene-77.png.asset.json";
import homeScene from "@/assets/scene-78.png.asset.json";
import shareScene from "@/assets/scene-79.png.asset.json";

// "The School Reopening Challenge" — 14 story days, GH₵50 to start, GH₵80 school bag.
// Data only: the engine in src/lib/scenario handles money, branching and delayed events.
export const schoolReopeningScenario: ScenarioDefinition = {
  id: "kwame-request",
  track: "save",
  title: "The School Reopening Challenge",
  subtitle: "14 days · School bag goal",
  description:
    "Two weeks before school reopens you have GH₵50 and want a GH₵80 school bag. Earn, save, spend and adjust your way through fourteen days.",
  totalDays: 14,
  goalLabel: "School Bag Goal",
  goalTarget: 80,
  startingAvailable: 50,
  startingSaved: 0,
  startNodeId: "plan-the-money",
  competencies: [
    "goal-setting",
    "saving",
    "earning",
    "needs-vs-wants",
    "spending-decisions",
    "borrowing-lending",
    "money-safety",
    "financial-resilience",
  ],
  closingReflection:
    "Money choices keep going after the day you make them. Noticing what happens next is what good money managers do.",
  intro: {
    title: "The School Reopening Challenge",
    body: "School reopens in 14 days. You have GH₵50 and your eye on a GH₵80 school bag — that is GH₵30 more than you have. Some days you will earn, some days you will be tempted, and some days life will surprise you. There are no wrong answers, only choices and what follows them.",
    image: playground.url,
    cta: "Start Day 1 🚀",
  },
  nodes: [
    {
      id: "plan-the-money",
      day: 1,
      topic: "Making a plan",
      place: "Home veranda",
      title: "Give your GH₵50 a plan",
      situation:
        "You count your cedis on the table: GH₵50. The bag costs GH₵80. Anything you put in the savings box is protected — only a big decision will take it out again.",
      question: "How much goes into the savings box today?",
      image: veranda.url,
      imageCaption: "Counting cedis at home",
      tip: "Money in your pocket disappears faster than money in the box. But you still need some for the week.",
      choices: [
        {
          id: "save-40",
          label: "Put GH₵40 in the box",
          description: "A bold start. Only GH₵10 left in your pocket.",
          icon: "🎯",
          effect: { transferToSaved: 40, competencies: { "goal-setting": 3, saving: 2 } },
          consequence: {
            decisionChip: "Decision: GH₵40 into the savings box",
            headline: "Here's what happened",
            title: "A strong start with a thin pocket",
            body: "Your goal is already halfway. Just remember that only GH₵10 is left for the whole week, so surprises will feel tight.",
            ledgerNote: "GH₵40 → savings box",
          },
          next: "earn-at-the-stall",
        },
        {
          id: "save-30",
          label: "Put GH₵30 in the box",
          description: "Balanced. GH₵20 stays available.",
          icon: "⚖️",
          effect: { transferToSaved: 30, competencies: { "goal-setting": 2, budgeting: 2 } },
          consequence: {
            decisionChip: "Decision: GH₵30 into the savings box",
            headline: "Here's what happened",
            title: "A balanced plan",
            body: "You protected a good amount and kept enough in your pocket for the small things the week will ask for.",
            ledgerNote: "GH₵30 → savings box",
          },
          next: "earn-at-the-stall",
        },
        {
          id: "save-20",
          label: "Put GH₵20 in the box",
          description: "Careful. GH₵30 stays available for the week.",
          icon: "👛",
          effect: { transferToSaved: 20, competencies: { budgeting: 1, "tracking-money": 1 } },
          consequence: {
            decisionChip: "Decision: GH₵20 into the savings box",
            headline: "Here's what happened",
            title: "Plenty in the pocket",
            body: "You have lots of spending money this week. Pocket money is easy to use up, so you will need to watch it closely.",
            ledgerNote: "GH₵20 → savings box",
          },
          next: "earn-at-the-stall",
        },
      ],
    },
    {
      id: "earn-at-the-stall",
      day: 2,
      topic: "Earning",
      place: "Auntie Adwoa's food stall",
      title: "An afternoon of work",
      situation:
        "Auntie Adwoa needs help washing bowls and serving customers. She will pay GH₵15 for the whole afternoon, or GH₵8 for one hour. Your friends are heading to the football pitch.",
      question: "How will you spend the afternoon?",
      image: marketScene.url,
      imageCaption: "Auntie Adwoa's stall",
      quote: {
        speaker: "Auntie Adwoa says",
        text: "If you work well today, I may call you again before school reopens!",
      },
      choices: [
        {
          id: "full-shift",
          label: "Work the full afternoon (GH₵15)",
          description: "Miss football, earn the most.",
          icon: "💪",
          effect: {
            available: 15,
            competencies: { earning: 3 },
            flags: { helpedStall: true },
          },
          consequence: {
            decisionChip: "Decision: You earned GH₵15",
            headline: "Here's what happened",
            title: "Honest work, honest cedis",
            body: "Your arms ached, but Auntie Adwoa smiled and said you work carefully. Earning is the fastest way to close a money gap.",
            ledgerNote: "+GH₵15 earned",
            laterHint: "Auntie Adwoa may need you again later this week…",
          },
          schedule: { inDays: 9, nodeId: "second-job", requiresFlag: "helpedStall" },
          next: "needs-vs-wants",
        },
        {
          id: "one-hour",
          label: "Work one hour (GH₵8)",
          description: "Earn a little, still catch the match.",
          icon: "⏱️",
          effect: { available: 8, competencies: { earning: 2, budgeting: 1 } },
          consequence: {
            decisionChip: "Decision: You earned GH₵8",
            headline: "Here's what happened",
            title: "A bit of both",
            body: "You helped for an hour, earned GH₵8 and still played football. Balancing work and rest is a real-life skill too.",
            ledgerNote: "+GH₵8 earned",
          },
          next: "needs-vs-wants",
        },
        {
          id: "play",
          label: "Go and play football",
          description: "No cedis today, a good time with friends.",
          icon: "⚽",
          effect: { competencies: { "financial-resilience": 1 } },
          consequence: {
            decisionChip: "Decision: You played football",
            headline: "Here's what happened",
            title: "Rest matters too",
            body: "You had a great match. Your goal did not move today, so other days will have to work a little harder.",
            ledgerNote: "No change",
          },
          next: "needs-vs-wants",
        },
      ],
    },
    {
      id: "needs-vs-wants",
      day: 4,
      topic: "Needs vs wants",
      place: "Stationery kiosk",
      title: "The list and the toffees",
      situation:
        "You need an exercise book for GH₵4 before school reopens. Beside the books, a packet of toffees costs GH₵6.",
      question: "What do you buy today?",
      image: marketScene.url,
      tip: "A need is something school or home really requires. A want is nice, but can wait.",
      choices: [
        {
          id: "book-only",
          label: "Buy only the exercise book",
          description: "GH₵4 for what you actually need.",
          icon: "📓",
          effect: { available: -4, competencies: { "needs-vs-wants": 3 } },
          consequence: {
            decisionChip: "Decision: Exercise book, GH₵4",
            headline: "Here's what happened",
            title: "Need first",
            body: "You have what school requires and your goal is untouched. The toffees are still there another day.",
            ledgerNote: "−GH₵4",
          },
          next: "kwame-request",
        },
        {
          id: "book-and-toffee",
          label: "Buy the book and the toffees",
          description: "GH₵10 for both.",
          icon: "🍬",
          effect: { available: -10, competencies: { "spending-decisions": 1 } },
          consequence: {
            decisionChip: "Decision: Book and toffees, GH₵10",
            headline: "Here's what happened",
            title: "A sweet afternoon",
            body: "You shared toffees with your cousin and everyone was happy. Your pocket is lighter, so the next few days matter more.",
            ledgerNote: "−GH₵10",
          },
          next: "kwame-request",
        },
        {
          id: "wait",
          label: "Wait — the book can come later",
          description: "Keep your cedis for now.",
          icon: "⏳",
          effect: { competencies: { "goal-setting": 1 }, flags: { needsBook: true } },
          consequence: {
            decisionChip: "Decision: Nothing bought today",
            headline: "Here's what happened",
            title: "Saved today, still needed tomorrow",
            body: "Your money stayed with you, but the exercise book is still on your school list. Needs usually come back.",
            ledgerNote: "No change",
          },
          next: "kwame-request",
        },
      ],
    },
    {
      id: "kwame-request",
      day: 6,
      topic: "Friendship & money dilemma",
      place: "Playground",
      title: "Kwame's Request",
      situation:
        "Kwame needs GH₵10 and promises to pay you back on Friday. You are also saving for your school bag.",
      question: "What would you like to do?",
      image: playground.url,
      imageCaption: "Under the mango tree at Accra D.A. Basic School",
      tip: "There are no wrong answers. Different choices lead to different real-life situations!",
      choices: [
        {
          id: "lend-10",
          label: "Lend Kwame GH₵10",
          description: "Help your friend with everything he asked for.",
          icon: "🤝",
          effect: {
            available: -10,
            flags: { lentToKwame: 10 },
            competencies: { "borrowing-lending": 1 },
          },
          consequence: {
            decisionChip: "Decision: You lent Kwame GH₵10",
            headline: "Here's what happened",
            title: "A kind choice and a real trade-off",
            body: "Helping someone can be important. But now you have less money available until Kwame pays you back.",
            image: veranda.url,
            imageCaption: "Veranda Reflections",
            ledgerNote: "−GH₵10 for Kwame",
            debtNote: "Kwame owes you GH₵10",
            laterHint: "Financial promises take time. Let's see what happens on Friday!",
          },
          schedule: { inDays: 3, nodeId: "repayment-day" },
          next: "keep-money-safe",
        },
        {
          id: "lend-5",
          label: "Lend Kwame GH₵5",
          description: "Share half and keep the rest available.",
          icon: "⚖️",
          effect: {
            available: -5,
            flags: { lentToKwame: 5 },
            competencies: { "borrowing-lending": 2, "goal-setting": 1 },
          },
          consequence: {
            decisionChip: "Decision: You lent Kwame GH₵5",
            headline: "Here's what happened",
            title: "Helping and still holding your plan",
            body: "Kwame thanked you and found the rest from his brother. You kept part of your pocket money for your own plan.",
            image: veranda.url,
            imageCaption: "Veranda Reflections",
            ledgerNote: "−GH₵5 for Kwame",
            debtNote: "Kwame owes you GH₵5",
            laterHint: "Kwame said he will bring your cedis back on Friday.",
          },
          schedule: { inDays: 3, nodeId: "repayment-day" },
          next: "keep-money-safe",
        },
        {
          id: "keep",
          label: "Keep the money for my goal",
          description: "Politely protect all your cedis for the school bag.",
          icon: "🛡️",
          effect: { competencies: { "goal-setting": 2, saving: 1 } },
          consequence: {
            decisionChip: "Decision: You kept your cedis",
            headline: "Here's what happened",
            title: "Protecting your promise to yourself",
            body: "You told Kwame kindly that your money is already promised to your school bag. He understood and asked his uncle instead.",
            image: veranda.url,
            imageCaption: "Veranda Reflections",
            ledgerNote: "No change",
          },
          next: "keep-money-safe",
        },
      ],
    },
    {
      id: "keep-money-safe",
      day: 7,
      topic: "Money safety",
      place: "Home",
      title: "Where will your money sleep?",
      situation:
        "Your cedis are folded in your pocket. Mum offers to keep the money on her Mobile Money wallet, or you can use the carved savings box with the little lock.",
      question: "Where will you keep your money this week?",
      image: homeScene.url,
      tip: "Safe, accessible, suitable — the best place is the one that fits your plan.",
      choices: [
        {
          id: "momo",
          label: "Mobile Money with Mum",
          description: "Safe and recorded, but not instant to reach.",
          icon: "📱",
          effect: { transferToSaved: 5, competencies: { "money-safety": 3, saving: 1 } },
          consequence: {
            decisionChip: "Decision: Mobile Money with Mum",
            headline: "Here's what happened",
            title: "Harder to spend by mistake",
            body: "Mum sent GH₵5 of your pocket money into her wallet for you and wrote it down. Money you cannot reach easily is money that stays.",
            ledgerNote: "GH₵5 → savings",
          },
          next: "water-errand",
        },
        {
          id: "box",
          label: "The locked savings box",
          description: "At home, easy to add to, easy to open.",
          icon: "🔒",
          effect: { competencies: { "money-safety": 2 } },
          consequence: {
            decisionChip: "Decision: The locked box at home",
            headline: "Here's what happened",
            title: "Close by and protected",
            body: "Your box sits on the shelf where you can see your progress. Just remember: what you can open easily, you can also empty easily.",
            ledgerNote: "No change",
          },
          next: "water-errand",
        },
        {
          id: "pocket",
          label: "Keep it in my pocket",
          description: "Always with you.",
          icon: "👖",
          effect: { available: -2, competencies: { "tracking-money": 1 } },
          consequence: {
            decisionChip: "Decision: Money stays in your pocket",
            headline: "Here's what happened",
            title: "GH₵2 slipped away",
            body: "A GH₵2 coin fell out during football. Pockets are handy, but they are the least safe place for goal money.",
            ledgerNote: "−GH₵2 lost",
          },
          next: "water-errand",
        },
      ],
    },
    {
      id: "water-errand",
      day: 8,
      topic: "Earning",
      place: "Neighbour's compound",
      title: "Maa Akos needs water fetched",
      situation:
        "Your neighbour Maa Akos will pay GH₵8 if you fetch four buckets of water before evening. It is hot, and the tap is far.",
      question: "Do you fetch the water?",
      image: homeScene.url,
      choices: [
        {
          id: "fetch",
          label: "Fetch the water (GH₵8)",
          description: "Hard work, real cedis.",
          icon: "🪣",
          effect: { available: 8, competencies: { earning: 2, "financial-resilience": 1 } },
          consequence: {
            decisionChip: "Decision: You earned GH₵8",
            headline: "Here's what happened",
            title: "Four buckets, eight cedis",
            body: "Your shoulders ached but your goal moved closer. Small jobs add up quickly when a deadline is near.",
            ledgerNote: "+GH₵8 earned",
          },
          next: "torn-sandal",
        },
        {
          id: "skip",
          label: "Not today",
          description: "Rest in the shade instead.",
          icon: "🌴",
          effect: {},
          consequence: {
            decisionChip: "Decision: You rested",
            headline: "Here's what happened",
            title: "A quiet afternoon",
            body: "You stayed in the shade with a book. Nothing came in today, so later days carry more of the work.",
            ledgerNote: "No change",
          },
          next: "torn-sandal",
        },
      ],
    },
    {
      id: "repayment-day",
      day: 9,
      topic: "Repayment dilemma",
      place: "School veranda",
      title: "Remember the money you lent Kwame?",
      situation:
        "Kwame planned to return everything today, but he only has part of it. He wants to bring the rest next week.",
      question: "What would you like to do next?",
      image: repaymentScene.url,
      imageCaption: "Partial repayment at the veranda",
      imageBadge: "Repayment day",
      quote: {
        speaker: "Kwame says",
        text: "Thank you so much for helping me on Tuesday. I only have GH₵5 today, but I will bring the rest next week.",
      },
      tip: "When people borrow, repayments are sometimes delayed or partial. Good money managers plan for that.",
      choices: [
        {
          id: "to-savings",
          label: "Put the GH₵5 into my savings box",
          description: "Send it straight to the school bag goal.",
          icon: "🐖",
          effect: { saved: 5, competencies: { saving: 2, "borrowing-lending": 1 } },
          consequence: {
            decisionChip: "Decision: Repayment went to savings",
            headline: "Here's what happened",
            title: "Straight to your goal",
            body: "The returned cedis went into the box right away, so they cannot quietly disappear into small spending.",
            ledgerNote: "+GH₵5 saved",
            debtNote: "Kwame still owes you GH₵5",
          },
          next: "torn-sandal",
        },
        {
          id: "to-pocket",
          label: "Keep the GH₵5 as pocket money",
          description: "Hold it for pencils or snacks this week.",
          icon: "👛",
          effect: { available: 5, competencies: { "tracking-money": 1 } },
          consequence: {
            decisionChip: "Decision: Repayment stays in pocket",
            headline: "Here's what happened",
            title: "Ready for this week",
            body: "You now have more available for school needs. Remember that pocket money disappears faster than box money.",
            ledgerNote: "+GH₵5 available",
            debtNote: "Kwame still owes you GH₵5",
          },
          next: "torn-sandal",
        },
        {
          id: "agree-date",
          label: "Agree a clear day for the rest",
          description: "Take the GH₵5 and set a date together.",
          icon: "💬",
          effect: {
            available: 5,
            competencies: { "borrowing-lending": 3, "financial-resilience": 1 },
            flags: { clearAgreement: true },
          },
          consequence: {
            decisionChip: "Decision: You agreed a clear day",
            headline: "Here's what happened",
            title: "A clear plan beats a vague promise",
            body: "You took what Kwame had and you both wrote down the day the rest will come. Now you can plan your school bag purchase.",
            ledgerNote: "+GH₵5 available",
            debtNote: "Kwame owes GH₵5 — due before reopening",
            laterHint: "Clear agreements protect friendships as well as money.",
          },
          schedule: { inDays: 3, nodeId: "final-repayment", requiresFlag: "clearAgreement" },
          next: "torn-sandal",
        },
      ],
    },
    {
      id: "torn-sandal",
      day: 10,
      topic: "Unexpected expense",
      place: "Roadside cobbler",
      title: "Your sandal strap snapped",
      situation:
        "On the way home your sandal breaks. The cobbler can fix it properly for GH₵8, or your father has glue that might hold for a while.",
      question: "How do you handle this surprise?",
      image: homeScene.url,
      tip: "Surprises happen to everyone. What matters is how you adjust.",
      choices: [
        {
          id: "pay-pocket",
          label: "Pay the cobbler from my pocket",
          description: "GH₵8 from available money.",
          icon: "🩴",
          effect: { available: -8, competencies: { "financial-resilience": 3, budgeting: 1 } },
          consequence: {
            decisionChip: "Decision: Fixed for GH₵8 from pocket",
            headline: "Here's what happened",
            title: "Handled without touching the goal",
            body: "Your sandal is strong again and your savings box never opened. That is exactly what pocket money is for.",
            ledgerNote: "−GH₵8",
          },
          next: "family-share",
        },
        {
          id: "pay-savings",
          label: "Take GH₵8 from the savings box",
          description: "Keep pocket money, slow the goal.",
          icon: "📦",
          effect: { saved: -8, competencies: { "financial-resilience": 1 } },
          consequence: {
            decisionChip: "Decision: GH₵8 out of the savings box",
            headline: "Here's what happened",
            title: "Your goal took the hit",
            body: "The sandal is fixed. Opening the box is allowed in an emergency, and now you know how it feels to rebuild.",
            ledgerNote: "−GH₵8 from savings",
          },
          next: "family-share",
        },
        {
          id: "glue",
          label: "Use Dad's glue for now",
          description: "Free, but it may break again.",
          icon: "🧴",
          effect: { competencies: { "spending-decisions": 1 } },
          consequence: {
            decisionChip: "Decision: A free repair at home",
            headline: "Here's what happened",
            title: "Saved today, uncertain tomorrow",
            body: "The glue holds for now. Cheap fixes sometimes last and sometimes cost more later — today you kept every cedi.",
            ledgerNote: "No change",
          },
          next: "family-share",
        },
      ],
    },
    {
      id: "second-job",
      day: 11,
      topic: "Earning again",
      place: "Auntie Adwoa's food stall",
      title: "Auntie Adwoa calls you back",
      situation:
        "Because you worked carefully before, Auntie Adwoa asks you to help with a big catering order. She offers GH₵18 for the evening.",
      question: "Do you take the work?",
      image: marketScene.url,
      imageBadge: "Because of Day 2",
      choices: [
        {
          id: "take-it",
          label: "Take the job (GH₵18)",
          description: "A late evening, a good earning day.",
          icon: "🍲",
          effect: { available: 18, competencies: { earning: 3, "financial-resilience": 1 } },
          consequence: {
            decisionChip: "Decision: You earned GH₵18",
            headline: "Here's what happened",
            title: "Good work brings more work",
            body: "Your careful help on Day 2 is why this chance came back to you. Reputation is part of earning.",
            ledgerNote: "+GH₵18 earned",
          },
          next: "family-share",
        },
        {
          id: "rest",
          label: "Rest this evening",
          description: "You are tired and homework is waiting.",
          icon: "😴",
          effect: { competencies: { "goal-setting": 1 } },
          consequence: {
            decisionChip: "Decision: You rested",
            headline: "Here's what happened",
            title: "Choosing rest is allowed",
            body: "You finished your homework and slept well. Your goal did not grow, and that is a trade-off you made on purpose.",
            ledgerNote: "No change",
          },
          next: "family-share",
        },
      ],
    },
    {
      id: "family-share",
      day: 12,
      topic: "Family & sharing",
      place: "Home",
      title: "Ama's school photo",
      situation:
        "Your little sister Ama needs GH₵5 for her school photo and Mum is short this week. Nobody is asking you — but you heard.",
      question: "What do you do?",
      image: shareScene.url,
      choices: [
        {
          id: "give-5",
          label: "Give Ama GH₵5",
          description: "Help your sister, slow your goal a little.",
          icon: "💛",
          effect: { available: -5, competencies: { "spending-decisions": 2 } },
          consequence: {
            decisionChip: "Decision: You gave Ama GH₵5",
            headline: "Here's what happened",
            title: "Sharing is a money choice too",
            body: "Ama beamed. Sharing costs cedis and builds something money cannot buy — your family knows they can count on you.",
            ledgerNote: "−GH₵5 shared",
          },
          next: "jersey-temptation",
        },
        {
          id: "give-2",
          label: "Give GH₵2 and help her earn the rest",
          description: "Share a little, work together.",
          icon: "🤲",
          effect: { available: -2, competencies: { "spending-decisions": 2, earning: 1 } },
          consequence: {
            decisionChip: "Decision: GH₵2 and a plan",
            headline: "Here's what happened",
            title: "Helping without emptying your plan",
            body: "You gave GH₵2 and helped Ama sell oranges for the rest. Two goals moved forward at once.",
            ledgerNote: "−GH₵2 shared",
          },
          next: "jersey-temptation",
        },
        {
          id: "stay-focused",
          label: "Keep my cedis for the bag",
          description: "Your goal is very close now.",
          icon: "🎯",
          effect: { competencies: { "goal-setting": 2 } },
          consequence: {
            decisionChip: "Decision: You kept your cedis",
            headline: "Here's what happened",
            title: "Focused on your promise",
            body: "Mum sorted it out another way. Staying focused is not unkind — and next time you may be the one who can help.",
            ledgerNote: "No change",
          },
          next: "jersey-temptation",
        },
      ],
    },
    {
      id: "final-repayment",
      day: 12,
      topic: "Promise kept",
      place: "Kwame's house",
      title: "Kwame brings the rest",
      situation: "Just as you agreed, Kwame arrives with the remaining GH₵5 in his hand.",
      question: "Where does this money go?",
      image: repaymentScene.url,
      imageBadge: "Agreement honoured",
      choices: [
        {
          id: "savings",
          label: "Straight into the savings box",
          icon: "🐖",
          effect: { saved: 5, competencies: { saving: 2, "borrowing-lending": 2 } },
          consequence: {
            decisionChip: "Decision: GH₵5 into savings",
            headline: "Here's what happened",
            title: "The agreement worked",
            body: "Because you set a clear day, the money came back and went straight to your goal.",
            ledgerNote: "+GH₵5 saved",
          },
          next: "family-share",
        },
        {
          id: "pocket",
          label: "Keep it available",
          icon: "👛",
          effect: { available: 5, competencies: { "tracking-money": 1 } },
          consequence: {
            decisionChip: "Decision: GH₵5 in pocket",
            headline: "Here's what happened",
            title: "Back in your hands",
            body: "Your pocket is healthier for the last days before reopening.",
            ledgerNote: "+GH₵5 available",
          },
          next: "family-share",
        },
      ],
    },
    {
      id: "jersey-temptation",
      day: 13,
      topic: "Temptation",
      place: "Makola Market",
      title: "A jersey at the market",
      situation:
        "A bright Black Stars jersey is on sale for GH₵25 — one day only. Your school bag money is sitting in your box.",
      question: "What would you like to do?",
      image: marketScene.url,
      tip: "Think about the promise you made yourself on Day 1.",
      choices: [
        {
          id: "buy-jersey",
          label: "Buy the jersey",
          description: "Take GH₵25 from wherever you can.",
          icon: "👕",
          effect: { saved: -25, competencies: { "spending-decisions": 1 } },
          consequence: {
            decisionChip: "Decision: You bought the jersey",
            headline: "Here's what happened",
            title: "A happy day and a longer road",
            body: "The jersey is lovely and you wore it home. Your school bag is further away now, so reopening day will look different.",
            ledgerNote: "−GH₵25 from savings",
          },
          next: "reopening-day",
        },
        {
          id: "sleep-on-it",
          label: "Sleep on it for one night",
          description: "Wait and see if you still want it tomorrow.",
          icon: "🌙",
          effect: { competencies: { "spending-decisions": 3, "goal-setting": 1 } },
          consequence: {
            decisionChip: "Decision: You waited one night",
            headline: "Here's what happened",
            title: "The pause did the work",
            body: "By morning the jersey mattered less than the bag. Waiting one night is a money superpower.",
            ledgerNote: "No change",
          },
          next: "reopening-day",
        },
        {
          id: "stay-course",
          label: "Walk past and stay on plan",
          description: "Keep every cedi for the bag.",
          icon: "🎯",
          effect: { competencies: { "goal-setting": 3, "financial-resilience": 1 } },
          consequence: {
            decisionChip: "Decision: You stayed on plan",
            headline: "Here's what happened",
            title: "You remembered your goal",
            body: "You walked past the stall with your plan intact. Tomorrow is reopening shopping day.",
            ledgerNote: "No change",
          },
          next: "reopening-day",
        },
      ],
    },
    {
      id: "reopening-day",
      day: 14,
      topic: "Reopening day",
      place: "Bag shop",
      title: "The last day before school reopens",
      situation:
        "You stand in front of the GH₵80 bag. Beside it is a smaller, sturdy bag for GH₵55. Everything you earned, saved, shared and spent brought you here.",
      question: "What will you do today?",
      image: marketScene.url,
      choices: [
        {
          id: "buy-goal-bag",
          label: "Buy the GH₵80 school bag",
          description: "Only possible if your saved money reaches GH₵80.",
          icon: "🎒",
          effect: { transferAllToSaved: true, competencies: { "goal-setting": 3 } },
          consequence: {
            decisionChip: "Decision: Reaching for the GH₵80 bag",
            headline: "Here's what happened",
            title: "You went for your goal",
            body: "If your box held enough, the bag is yours. If it did not quite reach, the shopkeeper kept it aside while you keep saving — either way, you know exactly where you stand.",
            ledgerNote: "Goal day",
          },
          ending: "went-for-it",
        },
        {
          id: "buy-smaller",
          label: "Buy the sturdy GH₵55 bag",
          description: "Adjust the plan and keep some savings.",
          icon: "🔁",
          effect: { competencies: { "financial-resilience": 3, budgeting: 2 } },
          consequence: {
            decisionChip: "Decision: The GH₵55 bag",
            headline: "Here's what happened",
            title: "Adjusting is a skill",
            body: "You walked into school with a strong bag and cedis still in your box. Changing a plan on purpose is not failing.",
            ledgerNote: "Plan adjusted",
          },
          ending: "adjusted",
        },
        {
          id: "keep-saving",
          label: "Wait and keep saving",
          description: "Use last term's bag a little longer.",
          icon: "⏳",
          effect: { competencies: { saving: 3, "goal-setting": 2 } },
          consequence: {
            decisionChip: "Decision: Keep saving",
            headline: "Here's what happened",
            title: "Patience with a plan",
            body: "Your old bag can manage a few more weeks, and your savings keep growing towards the bag you really want.",
            ledgerNote: "Savings protected",
          },
          ending: "still-saving",
        },
      ],
    },
  ],
  endings: [
    {
      id: "went-for-it",
      title: "You went for your goal",
      body: "You kept your eyes on the school bag for fourteen days of earning, sharing and surprises.",
      reflection: "Which day changed your plan the most? What would you do again next term?",
    },
    {
      id: "adjusted",
      title: "You adjusted your plan",
      body: "You chose a bag that fit the money you actually had, and you still have savings left.",
      reflection: "When is changing a plan a smart move rather than giving up?",
    },
    {
      id: "still-saving",
      title: "Your savings keep growing",
      body: "You did not buy today, and your money is still yours and still growing.",
      reflection: "What is your next small step towards the bag?",
    },
  ],
};
