import type { Lesson } from "@/lib/lessons/types";
import deskScene from "@/assets/checkin-20.png.asset.json";
import stallScene from "@/assets/checkin-21.png.asset.json";
import celebrationScene from "@/assets/checkin-22.png.asset.json";

// SAVE track lessons for TATI Junior (ages 8–12), set in Ghana.
// Pure data: no UI and no database access here.

export const saveLessons: Lesson[] = [
  {
    id: "meet-your-money",
    track: "save",
    title: "Meet Your Money",
    subtitle: "The four superpowers of every cedi",
    learningObjective: "Know the four things money can do: save, spend, share and plan.",
    estimatedMinutes: 4,
    illustration: deskScene.url,
    illustrationBadge: "Let's learn & grow",
    topic: "Money Basics",
    contentBlocks: [
      { type: "text", body: "Money can do four big things. Tap each one to see!" },
      {
        type: "cards",
        cards: [
          {
            id: "save",
            label: "SAVE",
            title: "Keep for later",
            body: "Keep for future needs and big dreams.",
            chip: "🐷 Piggy Bank",
            tone: "save",
            reveal: "Kwabena keeps GH₵2 from his pocket money every school day.",
          },
          {
            id: "spend",
            label: "SPEND",
            title: "Use today",
            body: "Buy what you need or want today.",
            chip: "🧺 Daily Needs",
            tone: "spend",
            reveal: "Ama buys her exercise book before the new term starts.",
          },
          {
            id: "share",
            label: "SHARE",
            title: "Give a little",
            body: "Help friends, family or your community.",
            chip: "🤎 Caring Heart",
            tone: "share",
            reveal: "Esi buys water for a classmate who forgot her bottle.",
          },
          {
            id: "plan",
            label: "PLAN",
            title: "Decide first",
            body: "Decide how to balance your money.",
            chip: "🎯 Smart Goals",
            tone: "plan",
            reveal: "Yaw writes his plan before he opens his money box.",
          },
        ],
      },
      {
        type: "text",
        body: "People earn money by working: selling at a stall, teaching, driving a trotro, fixing phones, or helping at home for pocket money.",
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt: "You have GH₵20 and spend GH₵6 on notebooks. How much remains?",
      chip: "Mental Math",
      options: [
        { id: "a", label: "GH₵12" },
        { id: "b", label: "GH₵14" },
        { id: "c", label: "GH₵26" },
      ],
      correctOptionId: "b",
      feedbackTitle: "Well reasoned!",
      feedback: "When you spend GH₵6, you have GH₵14 left for other goals.",
    },
    reflection: {
      prompt: "Which superpower do you use most right now?",
      placeholder: "I usually…",
    },
    xpReward: 20,
    competencies: ["earning", "saving"],
    nextLesson: "needs-vs-wants",
    ctaLabel: "Continue to Needs vs Wants",
  },
  {
    id: "needs-vs-wants",
    track: "save",
    title: "Need or Want: What's the Difference?",
    subtitle: "Spot what you truly need for school and health",
    learningObjective:
      "Tell the difference between a need and a want, and know it can change with the situation.",
    estimatedMinutes: 5,
    illustration: stallScene.url,
    illustrationBadge: "Every coin tells a story",
    topic: "Smart Decisions",
    contentBlocks: [
      {
        type: "list",
        title: "NEED",
        chip: "Essential",
        body: "Important for health, safety, school and daily life.",
        tone: "good",
        items: [
          { id: "books", label: "School books & pencils", icon: "📚" },
          { id: "water", label: "Clean drinking water", icon: "💧" },
          { id: "shoes", label: "Safe school shoes", icon: "👞" },
          { id: "meals", label: "Nutritious meals", icon: "🍲" },
        ],
      },
      {
        type: "list",
        title: "WANT",
        chip: "Fun extra",
        body: "Fun and enjoyable, but not essential right now.",
        tone: "warn",
        items: [
          { id: "icecream", label: "Sweet ice cream & soda", icon: "🍦" },
          { id: "game", label: "Game credits & toys", icon: "🎮" },
          { id: "stickers", label: "Stickers & treat packs", icon: "⚽" },
          { id: "jersey", label: "Second cool sports jersey", icon: "👕" },
        ],
      },
      {
        type: "tip",
        title: "TATI Wisdom",
        body: "Something can be a NEED in one situation and a WANT in another!",
        example:
          "A warm lunch is a need when you are hungry at school, but three extra packets of sweet biscuits is a want.",
      },
    ],
    activity: {
      kind: "sort",
      title: "Tap & Sort",
      instruction: "Tap what you think are essential NEEDS for school and health.",
      helper: "You can tap more than one item.",
      items: [
        { id: "book", label: "Exercise book & pen", note: "School need", price: 8, isNeed: true },
        { id: "water", label: "Chilled water", note: "Health need", price: 2, isNeed: true },
        { id: "coins", label: "Game coins", note: "Optional want", price: 5 },
        { id: "lolly", label: "Sweet ice lolly", note: "Treat / want", price: 3 },
        {
          id: "sandals",
          label: "School sandals",
          note: "Health & school",
          price: 15,
          isNeed: true,
        },
        { id: "shades", label: "Gold sunglasses", note: "Fun want", price: 12 },
      ],
      feedbackTitle: "Great eye!",
      feedback:
        "Books, drinking water and safe sandals help you learn and stay healthy each day. Toys and sweets are fun, but can wait for special treat times.",
    },
    knowledgeCheck: {
      id: "kc",
      prompt:
        "Is a box of mathematical drawing instruments a Need or a Want for your geometry exam?",
      chip: "Tap your answer",
      options: [
        { id: "need", label: "It's a Need" },
        { id: "want", label: "It's a Want" },
      ],
      correctOptionId: "need",
      feedbackTitle: "Yes!",
      feedback: "For the exam it is a need, because you cannot do the work without it.",
    },
    xpReward: 20,
    competencies: ["needs-vs-wants", "spending-decisions"],
    nextLesson: "set-a-goal",
    ctaLabel: "Next: Set a Savings Goal",
  },
  {
    id: "set-a-goal",
    track: "save",
    title: "Set a Savings Goal",
    subtitle: "The three golden questions for any goal",
    learningObjective: "Turn a wish into a goal with a what, a how much and a when.",
    estimatedMinutes: 5,
    illustration: deskScene.url,
    illustrationBadge: "TATI Goal Master Blueprint",
    topic: "Goal Setting",
    contentBlocks: [
      {
        type: "text",
        body: "Every successful saver in Accra knows: a goal isn't just a wish — it's an adventure with three simple steps!",
      },
      {
        type: "steps",
        steps: [
          {
            id: "what",
            label: "PILLAR 1",
            title: "WHAT am I saving for?",
            body: '"A sturdy, colourful school bag for Primary 5."',
          },
          {
            id: "how",
            label: "PILLAR 2",
            title: "HOW MUCH do I need?",
            body: "GH₵80 in total.",
            note: "I have GH₵50, so I need GH₵30 more.",
          },
          {
            id: "when",
            label: "PILLAR 3",
            title: "WHEN do I need it?",
            body: "In 14 days, before school reopening day!",
          },
        ],
      },
      {
        type: "stat",
        items: [
          { label: "Saved", value: "GH₵50" },
          { label: "Target", value: "GH₵80" },
          { label: "Days left", value: "14" },
        ],
      },
      {
        type: "highlight",
        body: "Breaking big goals into daily steps makes them easy to reach. GH₵30 in 14 days is about GH₵2.20 a day.",
        tone: "good",
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt: "Which one is a real goal?",
      options: [
        { id: "a", label: "I want a bag one day" },
        { id: "b", label: "GH₵80 school bag in 14 days" },
        { id: "c", label: "I like bags" },
      ],
      correctOptionId: "b",
      feedbackTitle: "Exactly!",
      feedback: "A goal names the thing, the amount and the day.",
    },
    reflection: {
      prompt: "What is your own goal, and by when?",
      placeholder: "I am saving GH₵… for… by…",
    },
    xpReward: 25,
    competencies: ["goal-setting", "saving"],
    nextLesson: "money-plan",
    ctaLabel: "See My Goal Progress",
  },
  {
    id: "money-plan",
    track: "save",
    title: "Make a Money Plan: Save, Spend, Share",
    subtitle: "Think about what you want your money to do before you spend it",
    learningObjective: "Split money into save, spend and share buckets on purpose.",
    estimatedMinutes: 5,
    topic: "Money Planning",
    contentBlocks: [
      {
        type: "cards",
        cards: [
          {
            id: "save",
            label: "SAVE",
            title: "Save for big goals",
            body: "Protected for the future, like your GH₵80 school bag.",
            chip: "Safe in the digital piggy bank",
            tone: "save",
          },
          {
            id: "spend",
            label: "SPEND",
            title: "Spend on everyday needs",
            body: "For items you need today or small agreed wants.",
            chip: "Pocket money in hand",
            tone: "spend",
          },
          {
            id: "share",
            label: "SHARE",
            title: "Share with community",
            body: "Helping family, classmates or giving to good causes.",
            chip: "Generosity & friends",
            tone: "share",
          },
        ],
      },
      {
        type: "highlight",
        body: "Remember! There is no single magic formula. Good money managers divide their money based on their current goals and needs.",
        tone: "info",
      },
    ],
    activity: {
      kind: "allocate",
      title: "Allocate your GH₵20 allowance",
      instruction:
        "Share your GH₵20 into the three jars however you think is best for your school goals.",
      total: 20,
      jars: [
        {
          id: "save",
          label: "SAVE jar",
          chip: "Priority",
          note: "Targeting school bag",
          icon: "🐷",
          tone: "save",
        },
        {
          id: "spend",
          label: "SPEND jar",
          chip: "Daily needs",
          note: "Snacks & school pencil",
          icon: "🛍️",
          tone: "spend",
        },
        {
          id: "share",
          label: "SHARE jar",
          chip: "Giving back",
          note: "Help a friend",
          icon: "❤️",
          tone: "share",
        },
      ],
      feedbackTitle: "Thoughtful balance!",
      feedback:
        "Putting more toward your school bag speeds up your goal, while keeping a little for daily needs and sharing shows wise discernment.",
    },
    xpReward: 25,
    competencies: ["budgeting", "saving"],
    nextLesson: "track-money",
    ctaLabel: "Lock In My Plan & Continue",
  },
  {
    id: "track-money",
    track: "save",
    title: "Keeping Track of Money",
    subtitle: "A simple ledger any saver can keep",
    learningObjective: "Record money in and money out so nothing goes missing.",
    estimatedMinutes: 4,
    topic: "Tracking Money",
    contentBlocks: [
      {
        type: "text",
        body: "Abena receives GH₵20 after helping her aunt at her food stall. By Friday she cannot remember where GH₵7 went. A tracker solves that.",
      },
      {
        type: "stat",
        items: [
          { label: "Money in", value: "GH₵20", note: "Stall help" },
          { label: "Money out", value: "GH₵7", note: "Snacks, pen" },
          { label: "Left", value: "GH₵13" },
        ],
      },
      {
        type: "tip",
        title: "Three-line tracker",
        body: "Date · What happened · Amount in or out. That's all you need in an exercise book.",
        example: "Mon · helped at stall · +GH₵20\nTue · meat pie · −GH₵3",
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt: "Abena had GH₵13 left, then saved GH₵5 into her box. How much is still in her hand?",
      options: [
        { id: "a", label: "GH₵5" },
        { id: "b", label: "GH₵8" },
        { id: "c", label: "GH₵18" },
      ],
      correctOptionId: "b",
      feedback: "GH₵13 minus GH₵5 leaves GH₵8 in hand, and GH₵5 safely saved.",
    },
    xpReward: 20,
    competencies: ["tracking-money", "budgeting"],
    nextLesson: "where-to-save",
  },
  {
    id: "where-to-save",
    track: "save",
    title: "Where Can I Save My Money?",
    subtitle: "Home, bank or mobile wallet",
    learningObjective: "Compare safe places to keep savings.",
    estimatedMinutes: 4,
    topic: "Saving",
    contentBlocks: [
      {
        type: "cards",
        cards: [
          {
            id: "home",
            label: "AT HOME",
            title: "Money box",
            body: "Easy to reach — and easy to spend. Keep it with a trusted adult.",
            tone: "spend",
            reveal: "Good for small amounts you are saving for a few weeks.",
          },
          {
            id: "momo",
            label: "MOBILE MONEY",
            title: "Mobile wallet",
            body: "A parent's wallet can hold your savings safely on the phone.",
            tone: "plan",
            reveal: "Keep the PIN secret. Only your parent should approve a withdrawal.",
          },
          {
            id: "bank",
            label: "BANK",
            title: "Savings account",
            body: "Very safe, harder to touch, and it can grow a little over time.",
            tone: "save",
            reveal: "Many Ghanaian banks have junior accounts opened by a parent.",
          },
        ],
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt: "Which place is hardest to spend from by accident?",
      options: [
        { id: "a", label: "Your pocket" },
        { id: "b", label: "A bank savings account" },
        { id: "c", label: "Under the mattress" },
      ],
      correctOptionId: "b",
      feedback: "The harder it is to reach, the more likely your goal survives.",
    },
    xpReward: 20,
    competencies: ["saving", "money-safety"],
    nextLesson: "mobile-money",
  },
  {
    id: "mobile-money",
    track: "save",
    title: "Mobile Money",
    subtitle: "Saving on the phone, safely",
    learningObjective: "Understand how mobile money works and how to stay safe with it.",
    estimatedMinutes: 4,
    topic: "Money Safety",
    contentBlocks: [
      {
        type: "text",
        body: "Mobile Money keeps cedis on a phone number instead of in your pocket. An agent gives cash in (deposit) or cash out (withdraw).",
      },
      {
        type: "steps",
        steps: [
          {
            id: "1",
            label: "STEP 1",
            title: "Cash in",
            body: "Your parent gives money to the agent and it appears on the wallet.",
          },
          {
            id: "2",
            label: "STEP 2",
            title: "Keep",
            body: "The savings stay on the phone until you need them.",
          },
          {
            id: "3",
            label: "STEP 3",
            title: "Cash out",
            body: "Your parent withdraws when it is time to buy your goal item.",
          },
        ],
      },
      {
        type: "highlight",
        body: "Never share a PIN — not with a friend, not with a caller who says they work for the network.",
        tone: "warn",
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt:
        "A stranger calls and says he sent money by mistake and needs your PIN. What do you do?",
      options: [
        { id: "a", label: "Give the PIN quickly" },
        { id: "b", label: "Tell a parent and share nothing" },
        { id: "c", label: "Send him some money back" },
      ],
      correctOptionId: "b",
      feedbackTitle: "Safe choice",
      feedback: "Real agents never ask for your PIN. Always tell a trusted adult.",
    },
    xpReward: 20,
    competencies: ["money-safety", "saving"],
    nextLesson: "bank-accounts",
  },
  {
    id: "bank-accounts",
    track: "save",
    title: "Bank Accounts",
    subtitle: "What happens to money in a bank",
    learningObjective: "Know what a savings account is and why savings can grow there.",
    estimatedMinutes: 4,
    topic: "Saving",
    contentBlocks: [
      {
        type: "text",
        body: "A bank keeps your money safe and writes down every cedi. A parent opens a junior savings account with your name on it.",
      },
      {
        type: "tip",
        title: "Interest",
        body: "Banks sometimes add a small extra amount for leaving your money with them. Your GH₵100 can quietly become a little more.",
      },
      {
        type: "highlight",
        body: "A passbook or SMS shows your balance, so nobody has to guess.",
        tone: "info",
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt: "Why do some savers choose a bank instead of a tin at home?",
      options: [
        { id: "a", label: "It is safer and recorded" },
        { id: "b", label: "It looks nicer" },
        { id: "c", label: "It is faster to spend" },
      ],
      correctOptionId: "a",
      feedback: "Safety and a clear record are the main reasons.",
    },
    xpReward: 20,
    competencies: ["saving", "money-safety"],
    nextLesson: "little-by-little",
  },
  {
    id: "little-by-little",
    track: "save",
    title: "Saving Little by Little",
    subtitle: "Small amounts, big results",
    learningObjective: "See how tiny regular savings add up to a goal.",
    estimatedMinutes: 3,
    illustration: celebrationScene.url,
    illustrationBadge: "Milestone power",
    topic: "Saving",
    contentBlocks: [
      { type: "text", body: "Kofi saves GH₵2 every school day. That is GH₵10 a week." },
      {
        type: "stat",
        items: [
          { label: "1 week", value: "GH₵10" },
          { label: "4 weeks", value: "GH₵40" },
          { label: "8 weeks", value: "GH₵80" },
        ],
      },
      {
        type: "highlight",
        body: "Saving the same small amount often beats waiting for one big gift.",
        tone: "good",
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt: "Esi saves GH₵3 a day for 10 days. How much has she saved?",
      options: [
        { id: "a", label: "GH₵13" },
        { id: "b", label: "GH₵30" },
        { id: "c", label: "GH₵300" },
      ],
      correctOptionId: "b",
      feedback: "GH₵3 × 10 days = GH₵30. Little by little wins.",
    },
    xpReward: 20,
    competencies: ["saving", "goal-setting"],
    nextLesson: "smart-spending",
  },
  {
    id: "smart-spending",
    track: "save",
    title: "Is a Sale Always a Good Deal?",
    subtitle: "Smart spending at the market",
    learningObjective: "Judge a discount against your own goals, not the price tag.",
    estimatedMinutes: 5,
    illustration: stallScene.url,
    illustrationBadge: "44% OFF",
    topic: "Smart Spending",
    contentBlocks: [
      {
        type: "text",
        body: "At Kwesi's sports stall, an Accra Stars jersey is 44% off: GH₵45 down to GH₵25. Is that automatically a smart buy for you right now?",
      },
      {
        type: "stat",
        items: [
          { label: "Sale price", value: "GH₵25" },
          { label: "Money left after", value: "GH₵55" },
          { label: "School bag goal", value: "GH₵80" },
        ],
      },
      {
        type: "cards",
        cards: [
          {
            id: "win",
            label: "REAL WIN",
            title: "When is it a real win?",
            body: "It saves money ONLY IF you already needed and planned for it.",
            tone: "save",
          },
          {
            id: "trap",
            label: "TRAP",
            title: "When is it a trap?",
            body: "If it takes away money you promised for your school bag, it is still a distraction.",
            tone: "spend",
          },
        ],
      },
      {
        type: "highlight",
        body: "TATI core takeaway: smart shoppers look at their total goals, not just the discount tag.",
        tone: "info",
      },
    ],
    activity: {
      kind: "choice",
      title: "Your call",
      instruction: "The jersey is GH₵25 today. What do you do?",
      options: [
        {
          id: "buy",
          label: "Buy it now",
          response:
            "You enjoy the jersey today, and the school bag moves 10 days further away. Every decision teaches us something.",
        },
        {
          id: "wait",
          label: "Keep saving for the bag",
          response: "Your goal stays on track and you can look again after reopening day.",
        },
        {
          id: "part",
          label: "Ask a parent first",
          response:
            "Talking it through is a strong habit — grown-ups can help you compare the goal and the offer.",
        },
      ],
    },
    xpReward: 25,
    competencies: ["spending-decisions", "needs-vs-wants"],
    nextLesson: "stop-think-choose",
    ctaLabel: "Learn the STOP • THINK • CHOOSE rule",
  },
  {
    id: "stop-think-choose",
    track: "save",
    title: "STOP • THINK • CHOOSE",
    subtitle: "Three quick checks before you spend",
    learningObjective: "Use a three-step rule before parting with money.",
    estimatedMinutes: 4,
    topic: "Smart Decisions",
    contentBlocks: [
      {
        type: "steps",
        steps: [
          {
            id: "stop",
            label: "STEP 1 · STOP",
            title: "Do I NEED or really WANT this?",
            body: "Take a breath. Is it an essential, or a sparkling temptation you'll forget tomorrow?",
            note: "Wait 10 seconds before handing over your coins.",
          },
          {
            id: "think",
            label: "STEP 2 · THINK",
            title: "Can I truly afford it right now?",
            body: "Look only at your loose pocket cash. Never touch coins already locked in your savings.",
            note: "GH₵45 pocket cash vs GH₵72.50 protected.",
          },
          {
            id: "choose",
            label: "STEP 3 · CHOOSE",
            title: "What happens to my goal if I buy it?",
            body: "Will spending delay your GH₵80 school bag before term starts?",
            note: "Only GH₵7.50 left to hit your goal!",
          },
        ],
      },
      {
        type: "tip",
        title: "Coach Kwame's rule",
        body: "\"Smart savers aren't the ones who never spend; they're the ones who check twice!\"",
      },
      {
        type: "highlight",
        body: '"Deciding not to spend today is choosing your bigger dream tomorrow."',
        tone: "good",
      },
    ],
    xpReward: 20,
    competencies: ["spending-decisions", "financial-resilience"],
    nextLesson: "borrow-and-lend",
  },
  {
    id: "borrow-and-lend",
    track: "save",
    title: "Borrowing and Lending",
    subtitle: "Money between friends",
    learningObjective: "Understand what borrowing costs and how to lend kindly and safely.",
    estimatedMinutes: 4,
    topic: "Borrowing & Lending",
    contentBlocks: [
      {
        type: "text",
        body: "Yaw borrows GH₵5 from Ama for a snack and promises to pay on Friday. Borrowing is a promise, not a gift.",
      },
      {
        type: "cards",
        cards: [
          {
            id: "before",
            label: "BEFORE BORROWING",
            title: "Ask three things",
            body: "Do I need it? When exactly will I pay back? What if I cannot?",
            tone: "plan",
          },
          {
            id: "lending",
            label: "BEFORE LENDING",
            title: "Lend only what you can spare",
            body: "Never lend money that belongs to your goal, and agree the payback day out loud.",
            tone: "share",
          },
        ],
      },
      {
        type: "highlight",
        body: "Keeping your promise builds trust — that is worth more than the GH₵5.",
        tone: "good",
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt: "A friend asks for GH₵10 from your school-bag savings. What is the wisest reply?",
      options: [
        { id: "a", label: "Give it, the goal can wait" },
        { id: "b", label: "Explain your goal and offer help another way" },
        { id: "c", label: "Say nothing and avoid them" },
      ],
      correctOptionId: "b",
      feedbackTitle: "Kind and clear",
      feedback: "You can care for a friend and still protect your goal.",
    },
    xpReward: 20,
    competencies: ["borrowing-lending", "spending-decisions"],
    nextLesson: "when-plans-change",
  },
  {
    id: "when-plans-change",
    track: "save",
    title: "When Money Plans Change",
    subtitle: "Bouncing back from surprises",
    learningObjective: "Adjust a savings plan when something unexpected happens.",
    estimatedMinutes: 4,
    topic: "Financial Resilience",
    contentBlocks: [
      {
        type: "text",
        body: "Akosua saved GH₵60 for her bag. Then her sandals tore and she had to spend GH₵15. Her plan changed — and that is normal.",
      },
      {
        type: "stat",
        items: [
          { label: "Before", value: "GH₵60" },
          { label: "Surprise cost", value: "−GH₵15" },
          { label: "New total", value: "GH₵45" },
        ],
      },
      {
        type: "tip",
        title: "Adjust, don't quit",
        body: "Add a little more each day, move the date, or choose a smaller first goal. You can adjust your plan.",
      },
      {
        type: "highlight",
        body: "A small emergency stash — even GH₵5 — softens surprises.",
        tone: "info",
      },
    ],
    reflection: {
      prompt: "What would you change if a surprise cost came up this week?",
      placeholder: "I would…",
    },
    xpReward: 20,
    competencies: ["financial-resilience", "budgeting"],
    nextLesson: "money-safety",
  },
  {
    id: "money-safety",
    track: "save",
    title: "Keeping Money Safe",
    subtitle: "Protect your cedis and your secrets",
    learningObjective: "Practise habits that keep savings safe from loss and tricks.",
    estimatedMinutes: 4,
    illustration: celebrationScene.url,
    illustrationBadge: "Safety Champion",
    topic: "Money Safety",
    contentBlocks: [
      {
        type: "list",
        title: "Safe habits",
        tone: "good",
        items: [
          { id: "adult", label: "Keep savings with a trusted adult, bank or wallet", icon: "🛡️" },
          { id: "count", label: "Count and record your money", icon: "🧮" },
          { id: "pin", label: "Keep PINs and passwords secret", icon: "🔒" },
          { id: "ask", label: "Ask a parent before any big payment", icon: "🙋🏾" },
        ],
      },
      {
        type: "highlight",
        body: "If an offer sounds too good to be true — double your cedis today! — it is a trick.",
        tone: "warn",
      },
    ],
    knowledgeCheck: {
      id: "kc",
      prompt: "Someone promises to double your GH₵20 by tomorrow. What do you do?",
      options: [
        { id: "a", label: "Hand over the money" },
        { id: "b", label: "Walk away and tell an adult" },
        { id: "c", label: "Give half only" },
      ],
      correctOptionId: "b",
      feedbackTitle: "Well spotted",
      feedback: "Nobody can promise to double money. Walking away protects your savings.",
    },
    xpReward: 25,
    competencies: ["money-safety", "financial-resilience"],
    ctaLabel: "Finish the SAVE lessons",
  },
];
