/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChildRouteRouteImport } from './routes/child/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParentRouteRouteImport } from './routes/parent/route'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AcademyAdminRouteImport } from './routes/academy/admin'
import { Route as AcademyCohortsRouteImport } from './routes/academy/cohorts'
import { Route as AcademyDashboardRouteImport } from './routes/academy/dashboard'
import { Route as AcademyLoginRouteImport } from './routes/academy/login'
import { Route as AcademyProfileRouteImport } from './routes/academy/profile'
import { Route as AcademySessionRouteImport } from './routes/academy/session'
import { Route as ChildHomeRouteImport } from './routes/child/home'
import { Route as ChildLearnRouteImport } from './routes/child/learn'
import { Route as ChildLoginRouteImport } from './routes/child/login'
import { Route as ChildProgressRouteImport } from './routes/child/progress'
import { Route as ChildResultsRouteImport } from './routes/child/results'
import { Route as ParentIndexRouteImport } from './routes/parent/index'
import { Route as ParentFeedbackRouteImport } from './routes/parent/feedback'
import { Route as ParentFeedbackReviewRouteImport } from './routes/parent/feedback-review'
import { Route as ParentMetricsRouteImport } from './routes/parent/metrics'
import { Route as AcademyCohortsChildIdRouteImport } from './routes/academy/cohorts/$childId'
import { Route as AcademySessionMonitorRouteImport } from './routes/academy/session/monitor'
import { Route as AcademySessionStartRouteImport } from './routes/academy/session/start'
import { Route as ChildAssessmentAssessmentIdRouteImport } from './routes/child/assessment.$assessmentId'
import { Route as ChildLessonLessonIdRouteImport } from './routes/child/lesson.$lessonId'
import { Route as ChildReflectionReflectionIdRouteImport } from './routes/child/reflection.$reflectionId'
import { Route as ChildScenarioScenarioIdRouteImport } from './routes/child/scenario.$scenarioId'
import { Route as ParentChildChildIdRouteImport } from './routes/parent/child.$childId'
import { Route as AuthenticatedLearnChildIdIndexRouteImport } from './routes/_authenticated/learn.$childId.index'
import { Route as AuthenticatedLearnChildIdFeedbackRouteImport } from './routes/_authenticated/learn.$childId.feedback'
import { Route as AuthenticatedLearnChildIdSummaryRouteImport } from './routes/_authenticated/learn.$childId.summary'
import { Route as AcademyAdminSchoolsIndexRouteImport } from './routes/academy/admin/schools/index'
import { Route as AcademyAdminSchoolsSchoolIdRouteImport } from './routes/academy/admin/schools/$schoolId'
import { Route as AcademyAdminSchoolsCreateRouteImport } from './routes/academy/admin/schools/create'
import { Route as AuthenticatedLearnChildIdAssessmentAssessmentIdRouteImport } from './routes/_authenticated/learn.$childId.assessment.$assessmentId'
import { Route as AuthenticatedLearnChildIdLessonLessonIdRouteImport } from './routes/_authenticated/learn.$childId.lesson.$lessonId'
import { Route as AuthenticatedLearnChildIdReflectionReflectionIdRouteImport } from './routes/_authenticated/learn.$childId.reflection.$reflectionId'
import { Route as AuthenticatedLearnChildIdScenarioScenarioIdRouteImport } from './routes/_authenticated/learn.$childId.scenario.$scenarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRouteRoute = ChildRouteRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRouteRoute = ParentRouteRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AcademyAdminRoute = AcademyAdminRouteImport.update({
  id: '/academy/admin',
  path: '/academy/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyCohortsRoute = AcademyCohortsRouteImport.update({
  id: '/academy/cohorts',
  path: '/academy/cohorts',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyDashboardRoute = AcademyDashboardRouteImport.update({
  id: '/academy/dashboard',
  path: '/academy/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyLoginRoute = AcademyLoginRouteImport.update({
  id: '/academy/login',
  path: '/academy/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyProfileRoute = AcademyProfileRouteImport.update({
  id: '/academy/profile',
  path: '/academy/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySessionRoute = AcademySessionRouteImport.update({
  id: '/academy/session',
  path: '/academy/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildHomeRoute = ChildHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ChildLearnRoute = ChildLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ChildLoginRoute = ChildLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ChildProgressRoute = ChildProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ChildResultsRoute = ChildResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentFeedbackRoute = ParentFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentFeedbackReviewRoute = ParentFeedbackReviewRouteImport.update({
  id: '/feedback-review',
  path: '/feedback-review',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentMetricsRoute = ParentMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ParentRouteRoute,
} as any)
const AcademyCohortsChildIdRoute = AcademyCohortsChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => AcademyCohortsRoute,
} as any)
const AcademySessionMonitorRoute = AcademySessionMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AcademySessionRoute,
} as any)
const AcademySessionStartRoute = AcademySessionStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AcademySessionRoute,
} as any)
const ChildAssessmentAssessmentIdRoute =
  ChildAssessmentAssessmentIdRouteImport.update({
    id: '/assessment/$assessmentId',
    path: '/assessment/$assessmentId',
    getParentRoute: () => ChildRouteRoute,
  } as any)
const ChildLessonLessonIdRoute = ChildLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ChildReflectionReflectionIdRoute =
  ChildReflectionReflectionIdRouteImport.update({
    id: '/reflection/$reflectionId',
    path: '/reflection/$reflectionId',
    getParentRoute: () => ChildRouteRoute,
  } as any)
const ChildScenarioScenarioIdRoute = ChildScenarioScenarioIdRouteImport.update({
  id: '/scenario/$scenarioId',
  path: '/scenario/$scenarioId',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ParentChildChildIdRoute = ParentChildChildIdRouteImport.update({
  id: '/child/$childId',
  path: '/child/$childId',
  getParentRoute: () => ParentRouteRoute,
} as any)
const AuthenticatedLearnChildIdIndexRoute =
  AuthenticatedLearnChildIdIndexRouteImport.update({
    id: '/learn/$childId/',
    path: '/learn/$childId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdFeedbackRoute =
  AuthenticatedLearnChildIdFeedbackRouteImport.update({
    id: '/learn/$childId/feedback',
    path: '/learn/$childId/feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdSummaryRoute =
  AuthenticatedLearnChildIdSummaryRouteImport.update({
    id: '/learn/$childId/summary',
    path: '/learn/$childId/summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AcademyAdminSchoolsIndexRoute =
  AcademyAdminSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AcademyAdminRoute,
  } as any)
const AcademyAdminSchoolsSchoolIdRoute =
  AcademyAdminSchoolsSchoolIdRouteImport.update({
    id: '/schools/$schoolId',
    path: '/schools/$schoolId',
    getParentRoute: () => AcademyAdminRoute,
  } as any)
const AcademyAdminSchoolsCreateRoute =
  AcademyAdminSchoolsCreateRouteImport.update({
    id: '/schools/create',
    path: '/schools/create',
    getParentRoute: () => AcademyAdminRoute,
  } as any)
const AuthenticatedLearnChildIdAssessmentAssessmentIdRoute =
  AuthenticatedLearnChildIdAssessmentAssessmentIdRouteImport.update({
    id: '/learn/$childId/assessment/$assessmentId',
    path: '/learn/$childId/assessment/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdLessonLessonIdRoute =
  AuthenticatedLearnChildIdLessonLessonIdRouteImport.update({
    id: '/learn/$childId/lesson/$lessonId',
    path: '/learn/$childId/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdReflectionReflectionIdRoute =
  AuthenticatedLearnChildIdReflectionReflectionIdRouteImport.update({
    id: '/learn/$childId/reflection/$reflectionId',
    path: '/learn/$childId/reflection/$reflectionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdScenarioScenarioIdRoute =
  AuthenticatedLearnChildIdScenarioScenarioIdRouteImport.update({
    id: '/learn/$childId/scenario/$scenarioId',
    path: '/learn/$childId/scenario/$scenarioId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/child': typeof ChildRouteRouteWithChildren
  '/parent': typeof ParentRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/academy/admin': typeof AcademyAdminRouteWithChildren
  '/academy/cohorts': typeof AcademyCohortsRouteWithChildren
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/login': typeof AcademyLoginRoute
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/session': typeof AcademySessionRouteWithChildren
  '/child/home': typeof ChildHomeRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/login': typeof ChildLoginRoute
  '/child/progress': typeof ChildProgressRoute
  '/child/results': typeof ChildResultsRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/feedback-review': typeof ParentFeedbackReviewRoute
  '/parent/metrics': typeof ParentMetricsRoute
  '/parent/': typeof ParentIndexRoute
  '/academy/cohorts/$childId': typeof AcademyCohortsChildIdRoute
  '/academy/session/monitor': typeof AcademySessionMonitorRoute
  '/academy/session/start': typeof AcademySessionStartRoute
  '/child/assessment/$assessmentId': typeof ChildAssessmentAssessmentIdRoute
  '/child/lesson/$lessonId': typeof ChildLessonLessonIdRoute
  '/child/reflection/$reflectionId': typeof ChildReflectionReflectionIdRoute
  '/child/scenario/$scenarioId': typeof ChildScenarioScenarioIdRoute
  '/parent/child/$childId': typeof ParentChildChildIdRoute
  '/learn/$childId/feedback': typeof AuthenticatedLearnChildIdFeedbackRoute
  '/learn/$childId/summary': typeof AuthenticatedLearnChildIdSummaryRoute
  '/academy/admin/schools/$schoolId': typeof AcademyAdminSchoolsSchoolIdRoute
  '/academy/admin/schools/create': typeof AcademyAdminSchoolsCreateRoute
  '/learn/$childId/': typeof AuthenticatedLearnChildIdIndexRoute
  '/academy/admin/schools/': typeof AcademyAdminSchoolsIndexRoute
  '/learn/$childId/assessment/$assessmentId': typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRoute
  '/learn/$childId/lesson/$lessonId': typeof AuthenticatedLearnChildIdLessonLessonIdRoute
  '/learn/$childId/reflection/$reflectionId': typeof AuthenticatedLearnChildIdReflectionReflectionIdRoute
  '/learn/$childId/scenario/$scenarioId': typeof AuthenticatedLearnChildIdScenarioScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/child': typeof ChildRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/academy/admin': typeof AcademyAdminRouteWithChildren
  '/academy/cohorts': typeof AcademyCohortsRouteWithChildren
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/login': typeof AcademyLoginRoute
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/session': typeof AcademySessionRouteWithChildren
  '/child/home': typeof ChildHomeRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/login': typeof ChildLoginRoute
  '/child/progress': typeof ChildProgressRoute
  '/child/results': typeof ChildResultsRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/feedback-review': typeof ParentFeedbackReviewRoute
  '/parent/metrics': typeof ParentMetricsRoute
  '/parent': typeof ParentIndexRoute
  '/academy/cohorts/$childId': typeof AcademyCohortsChildIdRoute
  '/academy/session/monitor': typeof AcademySessionMonitorRoute
  '/academy/session/start': typeof AcademySessionStartRoute
  '/child/assessment/$assessmentId': typeof ChildAssessmentAssessmentIdRoute
  '/child/lesson/$lessonId': typeof ChildLessonLessonIdRoute
  '/child/reflection/$reflectionId': typeof ChildReflectionReflectionIdRoute
  '/child/scenario/$scenarioId': typeof ChildScenarioScenarioIdRoute
  '/parent/child/$childId': typeof ParentChildChildIdRoute
  '/learn/$childId/feedback': typeof AuthenticatedLearnChildIdFeedbackRoute
  '/learn/$childId/summary': typeof AuthenticatedLearnChildIdSummaryRoute
  '/academy/admin/schools/$schoolId': typeof AcademyAdminSchoolsSchoolIdRoute
  '/academy/admin/schools/create': typeof AcademyAdminSchoolsCreateRoute
  '/learn/$childId': typeof AuthenticatedLearnChildIdIndexRoute
  '/academy/admin/schools': typeof AcademyAdminSchoolsIndexRoute
  '/learn/$childId/assessment/$assessmentId': typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRoute
  '/learn/$childId/lesson/$lessonId': typeof AuthenticatedLearnChildIdLessonLessonIdRoute
  '/learn/$childId/reflection/$reflectionId': typeof AuthenticatedLearnChildIdReflectionReflectionIdRoute
  '/learn/$childId/scenario/$scenarioId': typeof AuthenticatedLearnChildIdScenarioScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/child': typeof ChildRouteRouteWithChildren
  '/parent': typeof ParentRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/academy/admin': typeof AcademyAdminRouteWithChildren
  '/academy/cohorts': typeof AcademyCohortsRouteWithChildren
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/login': typeof AcademyLoginRoute
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/session': typeof AcademySessionRouteWithChildren
  '/child/home': typeof ChildHomeRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/login': typeof ChildLoginRoute
  '/child/progress': typeof ChildProgressRoute
  '/child/results': typeof ChildResultsRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/feedback-review': typeof ParentFeedbackReviewRoute
  '/parent/metrics': typeof ParentMetricsRoute
  '/parent/': typeof ParentIndexRoute
  '/academy/cohorts/$childId': typeof AcademyCohortsChildIdRoute
  '/academy/session/monitor': typeof AcademySessionMonitorRoute
  '/academy/session/start': typeof AcademySessionStartRoute
  '/child/assessment/$assessmentId': typeof ChildAssessmentAssessmentIdRoute
  '/child/lesson/$lessonId': typeof ChildLessonLessonIdRoute
  '/child/reflection/$reflectionId': typeof ChildReflectionReflectionIdRoute
  '/child/scenario/$scenarioId': typeof ChildScenarioScenarioIdRoute
  '/parent/child/$childId': typeof ParentChildChildIdRoute
  '/_authenticated/learn/$childId/feedback': typeof AuthenticatedLearnChildIdFeedbackRoute
  '/_authenticated/learn/$childId/summary': typeof AuthenticatedLearnChildIdSummaryRoute
  '/academy/admin/schools/$schoolId': typeof AcademyAdminSchoolsSchoolIdRoute
  '/academy/admin/schools/create': typeof AcademyAdminSchoolsCreateRoute
  '/_authenticated/learn/$childId/': typeof AuthenticatedLearnChildIdIndexRoute
  '/academy/admin/schools/': typeof AcademyAdminSchoolsIndexRoute
  '/_authenticated/learn/$childId/assessment/$assessmentId': typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRoute
  '/_authenticated/learn/$childId/lesson/$lessonId': typeof AuthenticatedLearnChildIdLessonLessonIdRoute
  '/_authenticated/learn/$childId/reflection/$reflectionId': typeof AuthenticatedLearnChildIdReflectionReflectionIdRoute
  '/_authenticated/learn/$childId/scenario/$scenarioId': typeof AuthenticatedLearnChildIdScenarioScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/child'
    | '/parent'
    | '/auth'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/academy/admin'
    | '/academy/cohorts'
    | '/academy/dashboard'
    | '/academy/login'
    | '/academy/profile'
    | '/academy/session'
    | '/child/home'
    | '/child/learn'
    | '/child/login'
    | '/child/progress'
    | '/child/results'
    | '/parent/feedback'
    | '/parent/feedback-review'
    | '/parent/metrics'
    | '/parent/'
    | '/academy/cohorts/$childId'
    | '/academy/session/monitor'
    | '/academy/session/start'
    | '/child/assessment/$assessmentId'
    | '/child/lesson/$lessonId'
    | '/child/reflection/$reflectionId'
    | '/child/scenario/$scenarioId'
    | '/parent/child/$childId'
    | '/learn/$childId/feedback'
    | '/learn/$childId/summary'
    | '/academy/admin/schools/$schoolId'
    | '/academy/admin/schools/create'
    | '/learn/$childId/'
    | '/academy/admin/schools/'
    | '/learn/$childId/assessment/$assessmentId'
    | '/learn/$childId/lesson/$lessonId'
    | '/learn/$childId/reflection/$reflectionId'
    | '/learn/$childId/scenario/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/child'
    | '/auth'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/academy/admin'
    | '/academy/cohorts'
    | '/academy/dashboard'
    | '/academy/login'
    | '/academy/profile'
    | '/academy/session'
    | '/child/home'
    | '/child/learn'
    | '/child/login'
    | '/child/progress'
    | '/child/results'
    | '/parent/feedback'
    | '/parent/feedback-review'
    | '/parent/metrics'
    | '/parent'
    | '/academy/cohorts/$childId'
    | '/academy/session/monitor'
    | '/academy/session/start'
    | '/child/assessment/$assessmentId'
    | '/child/lesson/$lessonId'
    | '/child/reflection/$reflectionId'
    | '/child/scenario/$scenarioId'
    | '/parent/child/$childId'
    | '/learn/$childId/feedback'
    | '/learn/$childId/summary'
    | '/academy/admin/schools/$schoolId'
    | '/academy/admin/schools/create'
    | '/learn/$childId'
    | '/academy/admin/schools'
    | '/learn/$childId/assessment/$assessmentId'
    | '/learn/$childId/lesson/$lessonId'
    | '/learn/$childId/reflection/$reflectionId'
    | '/learn/$childId/scenario/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/child'
    | '/parent'
    | '/auth'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/academy/admin'
    | '/academy/cohorts'
    | '/academy/dashboard'
    | '/academy/login'
    | '/academy/profile'
    | '/academy/session'
    | '/child/home'
    | '/child/learn'
    | '/child/login'
    | '/child/progress'
    | '/child/results'
    | '/parent/feedback'
    | '/parent/feedback-review'
    | '/parent/metrics'
    | '/parent/'
    | '/academy/cohorts/$childId'
    | '/academy/session/monitor'
    | '/academy/session/start'
    | '/child/assessment/$assessmentId'
    | '/child/lesson/$lessonId'
    | '/child/reflection/$reflectionId'
    | '/child/scenario/$scenarioId'
    | '/parent/child/$childId'
    | '/_authenticated/learn/$childId/feedback'
    | '/_authenticated/learn/$childId/summary'
    | '/academy/admin/schools/$schoolId'
    | '/academy/admin/schools/create'
    | '/_authenticated/learn/$childId/'
    | '/academy/admin/schools/'
    | '/_authenticated/learn/$childId/assessment/$assessmentId'
    | '/_authenticated/learn/$childId/lesson/$lessonId'
    | '/_authenticated/learn/$childId/reflection/$reflectionId'
    | '/_authenticated/learn/$childId/scenario/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ChildRouteRoute: typeof ChildRouteRouteWithChildren
  ParentRouteRoute: typeof ParentRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AcademyAdminRoute: typeof AcademyAdminRouteWithChildren
  AcademyCohortsRoute: typeof AcademyCohortsRouteWithChildren
  AcademyDashboardRoute: typeof AcademyDashboardRoute
  AcademyLoginRoute: typeof AcademyLoginRoute
  AcademyProfileRoute: typeof AcademyProfileRoute
  AcademySessionRoute: typeof AcademySessionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/academy/admin': {
      id: '/academy/admin'
      path: '/academy/admin'
      fullPath: '/academy/admin'
      preLoaderRoute: typeof AcademyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/cohorts': {
      id: '/academy/cohorts'
      path: '/academy/cohorts'
      fullPath: '/academy/cohorts'
      preLoaderRoute: typeof AcademyCohortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/dashboard': {
      id: '/academy/dashboard'
      path: '/academy/dashboard'
      fullPath: '/academy/dashboard'
      preLoaderRoute: typeof AcademyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/login': {
      id: '/academy/login'
      path: '/academy/login'
      fullPath: '/academy/login'
      preLoaderRoute: typeof AcademyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/profile': {
      id: '/academy/profile'
      path: '/academy/profile'
      fullPath: '/academy/profile'
      preLoaderRoute: typeof AcademyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/session': {
      id: '/academy/session'
      path: '/academy/session'
      fullPath: '/academy/session'
      preLoaderRoute: typeof AcademySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/home': {
      id: '/child/home'
      path: '/home'
      fullPath: '/child/home'
      preLoaderRoute: typeof ChildHomeRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/learn': {
      id: '/child/learn'
      path: '/learn'
      fullPath: '/child/learn'
      preLoaderRoute: typeof ChildLearnRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/login': {
      id: '/child/login'
      path: '/login'
      fullPath: '/child/login'
      preLoaderRoute: typeof ChildLoginRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/progress': {
      id: '/child/progress'
      path: '/progress'
      fullPath: '/child/progress'
      preLoaderRoute: typeof ChildProgressRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/results': {
      id: '/child/results'
      path: '/results'
      fullPath: '/child/results'
      preLoaderRoute: typeof ChildResultsRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/feedback': {
      id: '/parent/feedback'
      path: '/feedback'
      fullPath: '/parent/feedback'
      preLoaderRoute: typeof ParentFeedbackRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/feedback-review': {
      id: '/parent/feedback-review'
      path: '/feedback-review'
      fullPath: '/parent/feedback-review'
      preLoaderRoute: typeof ParentFeedbackReviewRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/metrics': {
      id: '/parent/metrics'
      path: '/metrics'
      fullPath: '/parent/metrics'
      preLoaderRoute: typeof ParentMetricsRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/academy/cohorts/$childId': {
      id: '/academy/cohorts/$childId'
      path: '/$childId'
      fullPath: '/academy/cohorts/$childId'
      preLoaderRoute: typeof AcademyCohortsChildIdRouteImport
      parentRoute: typeof AcademyCohortsRoute
    }
    '/academy/session/monitor': {
      id: '/academy/session/monitor'
      path: '/monitor'
      fullPath: '/academy/session/monitor'
      preLoaderRoute: typeof AcademySessionMonitorRouteImport
      parentRoute: typeof AcademySessionRoute
    }
    '/academy/session/start': {
      id: '/academy/session/start'
      path: '/start'
      fullPath: '/academy/session/start'
      preLoaderRoute: typeof AcademySessionStartRouteImport
      parentRoute: typeof AcademySessionRoute
    }
    '/child/assessment/$assessmentId': {
      id: '/child/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/child/assessment/$assessmentId'
      preLoaderRoute: typeof ChildAssessmentAssessmentIdRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/lesson/$lessonId': {
      id: '/child/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/child/lesson/$lessonId'
      preLoaderRoute: typeof ChildLessonLessonIdRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/reflection/$reflectionId': {
      id: '/child/reflection/$reflectionId'
      path: '/reflection/$reflectionId'
      fullPath: '/child/reflection/$reflectionId'
      preLoaderRoute: typeof ChildReflectionReflectionIdRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/scenario/$scenarioId': {
      id: '/child/scenario/$scenarioId'
      path: '/scenario/$scenarioId'
      fullPath: '/child/scenario/$scenarioId'
      preLoaderRoute: typeof ChildScenarioScenarioIdRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/parent/child/$childId': {
      id: '/parent/child/$childId'
      path: '/child/$childId'
      fullPath: '/parent/child/$childId'
      preLoaderRoute: typeof ParentChildChildIdRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/_authenticated/learn/$childId/': {
      id: '/_authenticated/learn/$childId/'
      path: '/learn/$childId'
      fullPath: '/learn/$childId/'
      preLoaderRoute: typeof AuthenticatedLearnChildIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/feedback': {
      id: '/_authenticated/learn/$childId/feedback'
      path: '/learn/$childId/feedback'
      fullPath: '/learn/$childId/feedback'
      preLoaderRoute: typeof AuthenticatedLearnChildIdFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/summary': {
      id: '/_authenticated/learn/$childId/summary'
      path: '/learn/$childId/summary'
      fullPath: '/learn/$childId/summary'
      preLoaderRoute: typeof AuthenticatedLearnChildIdSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/academy/admin/schools/': {
      id: '/academy/admin/schools/'
      path: '/schools'
      fullPath: '/academy/admin/schools/'
      preLoaderRoute: typeof AcademyAdminSchoolsIndexRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/academy/admin/schools/$schoolId': {
      id: '/academy/admin/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/academy/admin/schools/$schoolId'
      preLoaderRoute: typeof AcademyAdminSchoolsSchoolIdRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/academy/admin/schools/create': {
      id: '/academy/admin/schools/create'
      path: '/schools/create'
      fullPath: '/academy/admin/schools/create'
      preLoaderRoute: typeof AcademyAdminSchoolsCreateRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/_authenticated/learn/$childId/assessment/$assessmentId': {
      id: '/_authenticated/learn/$childId/assessment/$assessmentId'
      path: '/learn/$childId/assessment/$assessmentId'
      fullPath: '/learn/$childId/assessment/$assessmentId'
      preLoaderRoute: typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/lesson/$lessonId': {
      id: '/_authenticated/learn/$childId/lesson/$lessonId'
      path: '/learn/$childId/lesson/$lessonId'
      fullPath: '/learn/$childId/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLearnChildIdLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/reflection/$reflectionId': {
      id: '/_authenticated/learn/$childId/reflection/$reflectionId'
      path: '/learn/$childId/reflection/$reflectionId'
      fullPath: '/learn/$childId/reflection/$reflectionId'
      preLoaderRoute: typeof AuthenticatedLearnChildIdReflectionReflectionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/scenario/$scenarioId': {
      id: '/_authenticated/learn/$childId/scenario/$scenarioId'
      path: '/learn/$childId/scenario/$scenarioId'
      fullPath: '/learn/$childId/scenario/$scenarioId'
      preLoaderRoute: typeof AuthenticatedLearnChildIdScenarioScenarioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnChildIdFeedbackRoute: typeof AuthenticatedLearnChildIdFeedbackRoute
  AuthenticatedLearnChildIdSummaryRoute: typeof AuthenticatedLearnChildIdSummaryRoute
  AuthenticatedLearnChildIdIndexRoute: typeof AuthenticatedLearnChildIdIndexRoute
  AuthenticatedLearnChildIdAssessmentAssessmentIdRoute: typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRoute
  AuthenticatedLearnChildIdLessonLessonIdRoute: typeof AuthenticatedLearnChildIdLessonLessonIdRoute
  AuthenticatedLearnChildIdReflectionReflectionIdRoute: typeof AuthenticatedLearnChildIdReflectionReflectionIdRoute
  AuthenticatedLearnChildIdScenarioScenarioIdRoute: typeof AuthenticatedLearnChildIdScenarioScenarioIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnChildIdFeedbackRoute:
    AuthenticatedLearnChildIdFeedbackRoute,
  AuthenticatedLearnChildIdSummaryRoute: AuthenticatedLearnChildIdSummaryRoute,
  AuthenticatedLearnChildIdIndexRoute: AuthenticatedLearnChildIdIndexRoute,
  AuthenticatedLearnChildIdAssessmentAssessmentIdRoute:
    AuthenticatedLearnChildIdAssessmentAssessmentIdRoute,
  AuthenticatedLearnChildIdLessonLessonIdRoute:
    AuthenticatedLearnChildIdLessonLessonIdRoute,
  AuthenticatedLearnChildIdReflectionReflectionIdRoute:
    AuthenticatedLearnChildIdReflectionReflectionIdRoute,
  AuthenticatedLearnChildIdScenarioScenarioIdRoute:
    AuthenticatedLearnChildIdScenarioScenarioIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChildRouteRouteChildren {
  ChildHomeRoute: typeof ChildHomeRoute
  ChildLearnRoute: typeof ChildLearnRoute
  ChildLoginRoute: typeof ChildLoginRoute
  ChildProgressRoute: typeof ChildProgressRoute
  ChildResultsRoute: typeof ChildResultsRoute
  ChildAssessmentAssessmentIdRoute: typeof ChildAssessmentAssessmentIdRoute
  ChildLessonLessonIdRoute: typeof ChildLessonLessonIdRoute
  ChildReflectionReflectionIdRoute: typeof ChildReflectionReflectionIdRoute
  ChildScenarioScenarioIdRoute: typeof ChildScenarioScenarioIdRoute
}

const ChildRouteRouteChildren: ChildRouteRouteChildren = {
  ChildHomeRoute: ChildHomeRoute,
  ChildLearnRoute: ChildLearnRoute,
  ChildLoginRoute: ChildLoginRoute,
  ChildProgressRoute: ChildProgressRoute,
  ChildResultsRoute: ChildResultsRoute,
  ChildAssessmentAssessmentIdRoute: ChildAssessmentAssessmentIdRoute,
  ChildLessonLessonIdRoute: ChildLessonLessonIdRoute,
  ChildReflectionReflectionIdRoute: ChildReflectionReflectionIdRoute,
  ChildScenarioScenarioIdRoute: ChildScenarioScenarioIdRoute,
}

const ChildRouteRouteWithChildren = ChildRouteRoute._addFileChildren(
  ChildRouteRouteChildren,
)

interface ParentRouteRouteChildren {
  ParentFeedbackRoute: typeof ParentFeedbackRoute
  ParentFeedbackReviewRoute: typeof ParentFeedbackReviewRoute
  ParentMetricsRoute: typeof ParentMetricsRoute
  ParentIndexRoute: typeof ParentIndexRoute
  ParentChildChildIdRoute: typeof ParentChildChildIdRoute
}

const ParentRouteRouteChildren: ParentRouteRouteChildren = {
  ParentFeedbackRoute: ParentFeedbackRoute,
  ParentFeedbackReviewRoute: ParentFeedbackReviewRoute,
  ParentMetricsRoute: ParentMetricsRoute,
  ParentIndexRoute: ParentIndexRoute,
  ParentChildChildIdRoute: ParentChildChildIdRoute,
}

const ParentRouteRouteWithChildren = ParentRouteRoute._addFileChildren(
  ParentRouteRouteChildren,
)

interface AcademyAdminRouteChildren {
  AcademyAdminSchoolsSchoolIdRoute: typeof AcademyAdminSchoolsSchoolIdRoute
  AcademyAdminSchoolsCreateRoute: typeof AcademyAdminSchoolsCreateRoute
  AcademyAdminSchoolsIndexRoute: typeof AcademyAdminSchoolsIndexRoute
}

const AcademyAdminRouteChildren: AcademyAdminRouteChildren = {
  AcademyAdminSchoolsSchoolIdRoute: AcademyAdminSchoolsSchoolIdRoute,
  AcademyAdminSchoolsCreateRoute: AcademyAdminSchoolsCreateRoute,
  AcademyAdminSchoolsIndexRoute: AcademyAdminSchoolsIndexRoute,
}

const AcademyAdminRouteWithChildren = AcademyAdminRoute._addFileChildren(
  AcademyAdminRouteChildren,
)

interface AcademyCohortsRouteChildren {
  AcademyCohortsChildIdRoute: typeof AcademyCohortsChildIdRoute
}

const AcademyCohortsRouteChildren: AcademyCohortsRouteChildren = {
  AcademyCohortsChildIdRoute: AcademyCohortsChildIdRoute,
}

const AcademyCohortsRouteWithChildren = AcademyCohortsRoute._addFileChildren(
  AcademyCohortsRouteChildren,
)

interface AcademySessionRouteChildren {
  AcademySessionMonitorRoute: typeof AcademySessionMonitorRoute
  AcademySessionStartRoute: typeof AcademySessionStartRoute
}

const AcademySessionRouteChildren: AcademySessionRouteChildren = {
  AcademySessionMonitorRoute: AcademySessionMonitorRoute,
  AcademySessionStartRoute: AcademySessionStartRoute,
}

const AcademySessionRouteWithChildren = AcademySessionRoute._addFileChildren(
  AcademySessionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ChildRouteRoute: ChildRouteRouteWithChildren,
  ParentRouteRoute: ParentRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AcademyAdminRoute: AcademyAdminRouteWithChildren,
  AcademyCohortsRoute: AcademyCohortsRouteWithChildren,
  AcademyDashboardRoute: AcademyDashboardRoute,
  AcademyLoginRoute: AcademyLoginRoute,
  AcademyProfileRoute: AcademyProfileRoute,
  AcademySessionRoute: AcademySessionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
